app/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('carteira.urls')),
]

carteira/urls.py
from django.urls import path
from carteira import views

urlpatterns = [
    
     #DESH
    path('', views.desh, name='desh'),
    
    #CRUD ATIVO
    path('ativo/', views.AtivoRender.as_view(), name='list_ativo'),
    path('ativo/detail/<int:pk>', views.AtivoDetail.as_view(), name='detail_ativo'),
    path('ativo/create', views.CadastroAtivos.as_view(), name='create_ativo'),
    path('ativo/update/<int:pk>', views.AtivosUpdate.as_view(), name='update_ativo'),
    path('ativo/delete/<int:pk>', views.AtivoDelete.as_view(), name='delete_ativo'),
    
    #atualizar contacao
    path("ativo/atualizar-cotacao/", views.atualizar_cotacao, name="atualizar_cotacao"),
    path('get-setores/', views.get_setores_por_classe, name='get_setores'),
    
    #CRUD OPERACAO
    path('operacao/', views.OperacaoRender.as_view(), name='list_operacao'),
    path('operacao/create', views.CadastroOperacao.as_view(), name='create_operacao'),
    path('operacao/update/<int:pk>', views.OperacaoUpdate.as_view(), name='update_operacao'),
    path('operacao/delete/<int:pk>', views.OperacaoDelete.as_view(), name='delete_operacao'),
    path('operacao/filtrar-ativos/', views.filtrar_ativos, name='filtrar_ativos'),
    
    
    #CRUD PROVENTOS
    path('proventos/', views.ProventosRender.as_view(), name='list_proventos'),
    path('proventos/create', views.CadastroProventos.as_view(), name='create_proventos'),
    path('proventos/update/<int:pk>', views.ProventosUpdate.as_view(), name='update_proventos'),
    path('proventos/delete/<int:pk>', views.ProventosDelete.as_view(), name='delete_proventos'),
    
    #operaçao com proventos
    path('proventos/filtrar-ativos/', views.filtrar_ativos, name='filtrar_ativos'),
    path('proventos/agenda/', views.pgto_proventos, name='pgto_proventos'),
    path('proventos/pesquisar/', views.pesquisar_pagamento, name='pesquisar_proventos'),
    path('status-tarefa/<str:task_id>/', views.verificar_status_tarefa, name='verificar_status_tarefa'),
    
    #CRUD META
    path('metas/', views.MetaRender.as_view(), name='list_metas'),
    path('metas/create', views.CadastroMetas.as_view(), name='create_metas'),
    path('metas/update/<int:pk>', views.MetasUpdate.as_view(), name='update_metas'),
    path('metas/delete/<int:pk>', views.MetasDelete.as_view(), name='delete_metas'),
    
    #CRUD PLANO DE METAS
    path('plan-metas/', views.PlanMetasRender.as_view(), name='list_plan'),
    path('plan-metas/create', views.CadastroPlan.as_view(), name='create_plan'),
    path('plan-metas/delete/<int:pk>', views.PlanDelete.as_view(), name='delete_plan'),
    path('plan-metas/update/<int:pk>', views.update_qtd_ativo, name='update_plan'),
    path('plan-metas/filtrar-ativos/', views.filtrar_ativos, name='filtrar_plan'),
    
    #calculadaora
    path('plan-metas/calculadora/', views.calculadora_ativos, name='calculadora_plan'),
    path('plan-metas/calculadora/investimento/', views.create_valor_investido, name='create_investimento'),
    path('plan-metas/calculadora/<int:pk>', views.update_valor_investido, name='calc_investimento'),
    
    #CRUD PRECO TETO
    path('preco/', views.PrecoTetoRender.as_view(), name='list_preco_teto'),
    #path('preco/detail/<int:pk>', views.PrecoTetoDetail.as_view(), name='detail_preco_teto'),   
    path('preco/create', views.CadastroPrecoTeto.as_view(), name='create_preco_teto'),
    path('preco/update/<int:pk>', views.PrecoTetoUpdate.as_view(), name='update_preco_teto'),
    path('preco/delete/<int:pk>', views.PrecoTetoDelete.as_view(), name='delete_preco_teto'),
    path('preco/filtrar-ativos/', views.filtrar_ativos, name='filtrar_ativos'),
    
    
    #CRUD SETOR
    path('setor/create', views.CadastroSetor.as_view(), name='create_setor'),
    
]

carteira/models.py
from decimal import Decimal
from django.db import models
from django.utils.timezone import now
from django.contrib.auth.models import User

####################################### SETOR #############################################
class SetorAtivo(models.Model):
    class Meta:
        verbose_name = "Setor"
        verbose_name_plural = "Setor"
        ordering=['-id']
    fk_user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="user_setor", null=True)    
    setor = models.CharField(max_length=20, verbose_name='setor')
    setor_classe = models.CharField(max_length=20, verbose_name='classe', null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='criado em')
    update_at = models.DateTimeField(auto_now=True, verbose_name='atualizado em')
    
    def __str__(self):
        return self.setor

####################################### ATIVO #############################################
class Ativos(models.Model):
    class Meta:
        verbose_name = "Ativo"
        verbose_name_plural = "Ativos"
        ordering=['ativo']
            
    fk_user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="user_ativo", null=True,) #relacionando campo com a pk da tbl user
    ativo = models.CharField(max_length=250,verbose_name='nome do ativo')
    ticket = models.CharField(max_length=10)
    classe = models.CharField(max_length=10, null=False, blank=False)
    cnpj = models.CharField(max_length=20, verbose_name='CNPJ')
    setor = models.ForeignKey(SetorAtivo, on_delete=models.CASCADE, related_name="setor_ativo", verbose_name='Setor', null=True, blank=True, default=None) 
    corretora = models.ForeignKey('Corretora', on_delete=models.CASCADE, related_name='ativos_corretora', null=True, blank=True, verbose_name='Corretora')
    qtdAtivo = models.IntegerField(verbose_name='Qtd', blank=True, null= True)
    investimento= models.DecimalField(max_digits=20, decimal_places=2, blank=True, null= True)
    dividendos= models.DecimalField(max_digits=20, decimal_places=2, blank=True, null= True)
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='criado em')
    update_at = models.DateTimeField(auto_now=True, verbose_name='atualizado em')
        
    def __str__(self):
        return self.ticket
 
####################################### PROVENTOS #############################################   
class Proventos(models.Model):
    class Meta:
        verbose_name = "Proventos"
        verbose_name_plural = "Proventos"
        ordering=['-data_pgto']
        
    fk_user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="user_provento",  null=True) #relacionando campo com a pk da tbl user
    id_ativo = models.ForeignKey(Ativos, on_delete=models.CASCADE, null=True, blank=True, verbose_name="Ativos") #relacionando campo com a pk da tbl ativo
    classe = models.CharField(max_length=10, null=False, blank=False)
    status = models.CharField(max_length=10, null=False, blank=False, default="A PAGAR")
    tipo_provento = models.CharField(max_length=20, verbose_name='tipo de provento')
    valor_recebido = models.DecimalField(max_digits=20, decimal_places=2,verbose_name='valor recebido')
    data_pgto = models.DateField(verbose_name='data do pagamento')
    ano= models.IntegerField(verbose_name='ano', null=True, blank=True)
    mes= models.CharField(max_length=15, verbose_name='mês', null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='criado em')
    update_at = models.DateTimeField(auto_now=True, verbose_name='atualizado em')
    
    # Calcula o valor_total antes de salvar
    def save(self, *args, **kwargs):
    
         # Atualiza automaticamente o campo ano com base em data_operacao
        if self.data_pgto:
            self.mes = self.data_pgto.month
            
        if self.data_pgto:
            self.ano = self.data_pgto.year
            
            
          # Atualiza o status com base na data de pagamento
            if self.data_pgto <= now().date():
                self.status = "PAGO"
            else:
                self.status = "A PAGAR"
                
        super().save(*args, **kwargs)
    
    
    def __str__(self):
        return self.classe
    
####################################### OPERACAO #############################################    
class Operacao(models.Model):
    class Meta:
        verbose_name = "Operação"
        verbose_name_plural = "Operação"
        ordering=['-data_operacao']
        
    fk_user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="user_operacao",  null=True) #relacionando campo com a pk da tbl user
    id_ativo = models.ForeignKey(Ativos, on_delete=models.CASCADE, null=True, blank=True, verbose_name='Ativo') #relacionando campo com a pk da tbl ativo
    classe = models.CharField(max_length=10, null=False, blank=False, default="")
    tipo_operacao = models.CharField(max_length=20, verbose_name='tipo de operação', blank=True, null=True)
    data_operacao = models.DateField(verbose_name='data da operação')
    qtd = models.IntegerField(verbose_name='quantidade')
    valor_cota = models.DecimalField(max_digits=20, decimal_places=2,verbose_name='valor da cota', null=True, blank=True)
    fonte_recurso = models.CharField(max_length=20, verbose_name='Fonte de recurso', null=True, blank=True )
    valor_total = models.DecimalField(max_digits=20, decimal_places=2,verbose_name='Total da Operaçao', blank=True, null=True)
    mes= models.CharField(max_length=15, verbose_name='mês', null=True, blank=True)
    ano= models.IntegerField(verbose_name='ano', null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='criado em')
    update_at = models.DateTimeField(auto_now=True, verbose_name='atualizado em')
    
    
    # Calcula o valor_total antes de salvar
    def save(self, *args, **kwargs):
    
        if self.qtd and self.valor_cota:
            self.valor_total = self.qtd * self.valor_cota

        # Atualiza automaticamente o campo ano com base em data_operacao
        if self.data_operacao:
            self.ano = self.data_operacao.year
            
         # Atualiza automaticamente o campo ano com base em data_operacao
        if self.data_operacao:
            self.mes = self.data_operacao.month
            
        super().save(*args, **kwargs)
    
    
    def __str__(self):
        return self.classe
    
####################################### META #############################################    
class MetaAtivo(models.Model):
    class Meta:
        verbose_name = "Meta"
        verbose_name_plural = "Meta"
        ordering=['-ano']
        
    fk_user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="user_meta",  null=True) #relacionando campo com a pk da tbl user
    ano = models.IntegerField(verbose_name="Ano", null=True, blank=True)
    classe = models.CharField(max_length=10, null=False, blank=False, default="")
    meta_anual = models.IntegerField(verbose_name="Meta Anual", null=True, blank=True, default=0)
    meta_alcancada = models.IntegerField(verbose_name="Meta anual alçancada", null=True, blank=True)
    #status_anual = models.CharField(max_length=20, verbose_name="Status Anual", null=True, blank=True)
    meta_geral = models.IntegerField(verbose_name="Meta geral", null=True, blank=True, default=0)
    meta_geral_alcancada = models.IntegerField(verbose_name="Meta geral alcançada", null=True, blank=True, default=0)
    #status_geral = models.CharField(max_length=20, verbose_name="Status Anual", null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='criado em')
    update_at = models.DateTimeField(auto_now=True, verbose_name='atualizado em')

    def __str__(self):
        return self.classe


####################################### PLANEJAMENTO DE METAS aTIVOS#############################################    
class PlanMetas(models.Model):
    class Meta:
        verbose_name = "Planejamento das metas"
        verbose_name_plural = "Planejamento das metas"
        
    fk_user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="user_meta_ativo",  null=True) #relacionando campo com a pk da tbl user
    id_ativo = models.ForeignKey(Ativos, on_delete=models.CASCADE, null=True, blank=True, verbose_name="Ativos") #relacionando campo com a pk da tbl ativo
    classe = models.CharField(max_length=10, null=False, blank=False, default="")
    qtd = models.IntegerField(verbose_name="Quantidade", default=0, blank=True, null=True)   
    qtd_calc = models.IntegerField( default=0, blank=True, null=True)   #campo utilizado na tela caluladora
    from decimal import Decimal
    prov_cota = models.DecimalField(max_digits=20, decimal_places=2,verbose_name='proventos', blank=True, null=True, default=Decimal('0.00'))  
    ano = models.IntegerField(verbose_name="Ano", null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='criado em')
    update_at = models.DateTimeField(auto_now=True, verbose_name='atualizado em')
    
    def __str__(self):
        return self.classe

from decimal import Decimal

class PlanMetasCalc(models.Model):
    fk_user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="user_meta_plan_calc",  null=True)
    classe = models.CharField(max_length=10, null=False, blank=False, default="")
    valor_investido = models.DecimalField(max_digits=20, decimal_places=2, blank=True, null=True, default=Decimal('0.00'))  
    saldo = models.DecimalField(max_digits=20, decimal_places=2, blank=True, null=True, default=Decimal('0.00'))  


####################################### PREÇO TETO #############################################    
class PrecoTeto(models.Model):
    class Meta:
        verbose_name = "Preço teto"
        verbose_name_plural = "Preço teto"
        

carteira/views/aux_views.py
from carteira.models import SetorAtivo, Ativos
from django.http import JsonResponse
from utils.cotacao import obter_cotacao
from django.core.cache import cache

#FUNÇÕES GERAIS
def atualizar_cotacao(request):
    """Remove os dados do cache e busca novas cotações."""
    cache_key = "cotacao_key"
    
    # Obtém os ativos do usuário logado
    ativos = Ativos.objects.filter(fk_user_id=request.user.id)
    tickers = [ativo.ticket for ativo in ativos]

    # Força a atualização das cotações
    novas_cotacoes = obter_cotacao(tickers)
    cache.set(cache_key, novas_cotacoes, timeout=600)  # Armazena por 10 minutos
    return JsonResponse({"status": "success", "mensagem": "Cotações atualizadas com sucesso!"})


#funççao que filtra o setor por classe no formulario cadastro de ativos
def get_setores_por_classe(request):
    classe = request.GET.get('classe')
    user = request.user
    setores = SetorAtivo.objects.filter(fk_user=user, setor_classe=classe).values('id', 'setor')
    setores = SetorAtivo.objects.filter(setor_classe=classe).values('id', 'setor')

    return JsonResponse(list(setores), safe=False)


def filtrar_ativos(request):
    classe = request.GET.get('classe', '')
    
    # Filtra os ativos com base na classe
    ativos = Ativos.objects.filter(classe=classe, fk_user_id=request.user.id,)
    
    # Prepara a resposta em formato JSON
    ativos_data = [{'id': ativo.pk, 'nome': ativo.ticket} for ativo in ativos]
    return JsonResponse({'ativos': ativos_data})

carteira/views/home.py
import json
import locale
from django.shortcuts import render
from carteira.dados_graficos import metrics_charts_home


def desh(request):
    id_user = request.user.id  # ID do usuário autenticado
    filter = request.GET.get('ativo') if request.GET.get('ativo') else "FII"
    patrimonio_por_classe = metrics_charts_home.metrica_patrimonio(id_user)["patrimonio_por_classe"]
    render_grafico = True  # Ou False, se não for a página que deve renderizar o gráfico
    context = {
        #dados para os gráficoos 
        'ativo_por_classe': json.dumps(metrics_charts_home.grafico_ativo_por_classe(id_user)),  # Converte para JSON
        'ativo_por_setor': json.dumps(metrics_charts_home.grafico_ativo_por_setor(id_user,filter)), 
        'patrimonio': json.dumps({
            "classe": list(patrimonio_por_classe.keys()),  # Converte para JSON
            "valores": list(patrimonio_por_classe.values()),
    
            }),  
        'proventos_mensais': json.dumps(metrics_charts_home.grafico_proventos_mensais(id_user)),  # Converte para JSON
        'composicao_dividendos': json.dumps(metrics_charts_home.grafico_composicao_dividendos(id_user)),  # Converte para JSON
    
        #dados de metricas
        'metricas_patrimonio':metrics_charts_home.metrica_patrimonio(id_user),
        'metricas_dividendos': metrics_charts_home.metrica_dividendos(id_user),  # Adicionei a métrica de dividendos aqui    
        
        #variaveis de controle
        'render_grafico': render_grafico  # Variável de controle para renderizar o script javaScript
       
    }
    print(context['proventos_mensais'])
    return render(request, 'home/home.html', context)

carteira/templates/preco_teto/detail.html
<tr id="trExpense">
        <td>{{ form.id_ativo }}</td>
        <td>{{ form.classe }}</td>
        <td>{{ form.rentabilidade }}</td>
        {% if form.classe.value != "AÇÃO" %}
            <td>{{ form.ipca }}</td>
        {% endif %}
        <td>{{ lists.cotacao }}</td>
        <td>{{ lists.preco_teto|floatformat:2 }}</td>  <!-- Exibindo o preco_teto calculado -->
        <td>{{ lists.diferenca|floatformat:2 }}</td>   <!-- Exibindo a diferença -->
        <td>{{ lists.margem_seguranca|floatformat:2 }}</td>  <!-- Exibindo a margem de segurança -->
        <td>{{ lists.recomendacao }}</td>  <!-- Exibindo a recomendação -->

        <td class="text-center">
            <button 
              type="submit"
              class="btn btn-success"
              hx-post="{% url 'update_preco_teto' object.pk %}"
              hx-target="#trExpense"
              hx-swap="outerHTML"
              hx-headers='{"X-CSRFToken": "{{ csrf_token }}"}'
            >
              OK
            </button>
            <button
              class="btn btn-danger"
              hx-get="{% url 'update_preco_teto' object.pk %}"
              hx-target="#trExpense"
              hx-swap="outerHTML"
            >
              <i class="fa fa-close">X</i>
            </button>
</tr>

carteira/templates/preco_teto/detail_table.html
<tr hx-target="this" hx-swap="outerHTML">
    <td>{{ list.ativo }}</td>
    <td>{{ list.classe }}</td>
    <td>{{ list.rentabilidade }}</td>
    {% comment %} {% if request.GET.name == "FII" %} {% endcomment %}
        <td>{{ list.ipca }}</td>
    {% comment %} {% endif %} {% endcomment %}
    <td>{{ list.cotacao }}</td>
       <td>R$ {{ list.preco_teto|floatformat:2 }}</td> <!-- Formato de moeda -->
       <td  class="{% if list.diferenca > 0 %}text-success{% else %}text-danger{% endif %}">R$ {{ list.diferenca|floatformat:2 }}</td> <!-- Formato de moeda -->
       <td class="{% if list.diferenca < 0 %}text-success{% else %}text-danger{% endif %} text-center">{{ list.margem_seguranca|floatformat:2 }}%</td>
       <td class="{% if list.diferenca < 0 %}bg-success{% else %}bg-danger{% endif %}">{{ list.recomendacao }}</td>
        <td style="width:8em">

        <!--btn visualizar-->
        {% comment %} <a href="#" class="btn btn-info btn-sm"><i class="bi bi-eye-fill"></i></a> {% endcomment %}

        <!--btn Atualizar-->
         <!--btn Atualizar-->
         <a href="#" class="btn btn-warning btn-sm" data-bs-toggle="modal" 
         data-bs-target="#cadastroModal"
         hx-get = {% url "update_preco_teto" list.pk %}
         hx-target = "#addContent"
         hx-swap = "innerHTML"
         ><i class="bi bi-pencil-fill"></i></a>

        
{% comment %} 
          <!--btn Atualizar-->
          <a href="#" class="btn btn-warning btn-sm" data-bs-toggle="modal" 
          data-bs-target="#cadastroModal"
          hx-get = {% url "update_preco_teto" list.pk %}
          hx-target = "#addContent"
          hx-swap = "innerHTML"
          ><i class="bi bi-pencil-fill"></i></a> {% endcomment %}

        <!--btn deleter-->
        <a  onclick="modal(this)" 
        data-page="preco" 
        data-name="{{list.ativo}}" 
        data-id="{{list.pk}}"
         href="#" 
         class="btn btn-danger btn-sm"><i class="bi bi-trash-fill"></i></i></a>
    </td>
</tr>

carteira/templates/preco_teto/form_edit.html
<div class="modal-header">
    <h5 class="modal-title" id="cadastroModalLabel">
      Editar rentabilidade 
    </h5>
    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Fechar"></button>
</div>

<div class="modal-body">
    <!-- Formulário de Cadastro -->
    <form method="POST" 
          action="{% url 'update_preco_teto' form.instance.pk %}">
        {% csrf_token %}
        
        <div class="mb-3" style="display:none">
            <label>Classe do ativo</label>
            {{form.classe}}
        
        </div>

        <div class="mb-3">
            <label>Ativo</label>
            {{form.id_ativo}}
        </div>

        <div class="mb-3">
            <label>Rentabilidade desejada</label>
            {{form.rentabilidade}}
        </div>


        {% if form.classe.value != "Ação" %}
        <div class="mb-3" >
            <label>Prêmio de risco (Tesouro Direto 2045)</label>
            {{form.ipca}}
        </div>
        {% endif %}

        <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal"><i class="bi bi-x-lg"></i> Fechar</button>
            <button type="submit" class="btn btn-primary">{% if form.instance.pk %}<i class="bi bi-arrow-clockwise"></i>  Atualizar{% else %}   <i class="bi bi-person-plus me-1"></i> CadastrarCadastrar{% endif %}</button>
        </div>
    </form>
</div>

carteira/templates/preco_teto/forms.html
<div class="modal-header">
    <h5 class="modal-title" id="cadastroModalLabel">
        {% if form.instance.pk %}
            Editar Ativo
        {% else %}
            Inserir Ativo
        {% endif %}
    </h5>
    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Fechar"></button>
</div>

<div class="modal-body">
    <!-- Formulário de Cadastro -->
    <form method="POST" id="form-preco-teto" data-url="/preco"
          action="{% url 'create_preco_teto' %}">
        {% csrf_token %}
        
        <div class="mb-3">
            <label>Classe do ativo</label>
            <select id="id_classe" name="classe" class="form-control" onchange="hiddenCampoIpca()">
                {% for value, label in form.fields.classe.choices %}
                <option value="{{ value }}" {% if form.classe.value == value %}selected{% endif %}>{{ label }}</option>
                {% endfor %}
            </select>
        </div>

        <div class="mb-3">
            <label>Ativo</label>
            <select id="id_id_ativo" name="id_ativo" class="form-control">
                <option value="">Selecione uma classe primeiro...</option>
            </select>
        </div>

        <div class="mb-3">
            <label>Rentabilidade desejada</label>
            {{form.rentabilidade}}
        </div>

        <div class="mb-3" id="container_ipca">
            <label>Prêmio de risco (Tesouro Direto 2045)</label>
            {{form.ipca}}
        </div>

        <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal"> <i class="bi bi-x-lg"></i> Fechar</button>
            <button type="submit" class="btn btn-primary">{% if form.instance.pk %}<i class="bi bi-arrow-clockwise"></i>  Atualizar{% else %}  <i class="bi bi-floppy me-1"></i> Salvar{% endif %}</button>
        </div>
    </form>
</div>

carteira/templates/preco_teto/list.html
{% extends 'global/base.html' %}
{% block title %}
  Preço Teto
{% endblock %}
{% block content %}
  {% include 'global/componentes/menssage.html' %}
  <p id="successMessageCotacao" style="display: none;" class="alert alert-success">
    <!-- A mensagem será inserida aqui -->
  </p>


    {% if lists %}
      {% include 'preco_teto/table.html' %}
    {% else %}
      <p class="h3">Nenhum registro encontrado.</p>
    {% endif %}

    {% include 'global/componentes/pagination.html' %}
    {% include 'global/componentes/modal_forms.html' %}
  
{% endblock %}

carteira/templates/preco_teto/table.html
<div class="row g-4 card">
  <ul class="nav nav-tabs  nav-pills" id="metaTabs" role="tablist">
    <li class="nav-item" role="presentation">
      <button class="nav-link active" id="fii-tab" data-bs-toggle="tab" data-bs-target="#fii" type="button" role="tab">PREÇO TETO FII</button>
    </li>
    <li class="nav-item" role="presentation">
      <button class="nav-link" id="acoes-tab" data-bs-toggle="tab" data-bs-target="#acao" type="button" role="tab">PREÇO TETO AÇÕES</button>
    </li>
  </ul>

  <!-- ENVOLVA AS TABS AQUI -->
  <div class="tab-content">
    <div class="tab-pane fade show active" id="fii" role="tabpanel">
      {% include 'preco_teto/partials/table_fii.html' %}
    </div>

    <div class="tab-pane fade" id="acao" role="tabpanel">
      {% include 'preco_teto/partials/table_acao.html' %}
    </div>
  </div>
</div>